[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on  = "K"
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on  = "J"
run = "plugin parent-arrow 1"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "cd ~/Desktop"
desc = "go ~/Desktop"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Documents/PDRA/NU"
desc = "go Projects"

[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd ~/Mount"
desc = "go mount folder"

[[mgr.prepend_keymap]]
on   = [ "g", "v" ]
run  = "cd /Volumes/Mac/"
desc = "go Volumes"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = [ ":" ]
run = "plugin custom-shell zsh"
desc = "Run zsh"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-current"
desc = "Show or hide the preview pane"
